# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

continuation_prompt = "[ï”ï” ](bold fg:yellow)"

format = """
$directory \
($git_branch $git_commit ($git_state )$git_metrics$git_status)\
$c$golang$java$lua$python$rust\
$fill\
$time
($sudo$hostname$username )$character
"""

# format = """
# ([î‚¶](fg:blue)($sudo )($hostname$username)[î‚´](fg:blue) )\
# [î‚¶](fg:blue)$directory[î‚´](fg:blue) \
# [î‚¶](fg:blue)($git_branch $git_commit ($git_state )$git_metrics$git_status)[î‚´](fg:blue)\
# $c$golang$java$lua$python$rust\
# $fill\
# $time
# $character
# """

# # Style String Options
# bold
# italic
# underline
# dimmed
# inverted  # Inverts the foreground and background colors
# blink
# hidden
# strikethrough
# bg:<color>
# fg:<color>
# <color>
# none

palette = "catppuccin-mocha"
[palettes.catppuccin-mocha]
base = "#1E1E2E"
blue = "#89B4FA"
crust = "#11111B"
cyan = "#00FFFF"
darkblue = "#545AA7"
flamingo = "#F2CDCD"
green = "#A6E3A1"
green2 = "#1dd3b0"
lavender = "#B4BEFE"
mantle = "#181825"
maroon = "#EBA0AC"
mauve = "#CBA6F7"
overlay1 = "#7F849C"
overlay2 = "#9399b2"
peach = "#FAB387"
pink = "#F5C2E7"
red = "#F38BA8"
rojo = "#d81159"
rosewater = "#F5E0DC"
sapphire = "#74C7EC"
sky = "#89DCEB"
subtext0 = "#A6ADC8"
subtext1 = "#BAC2DE"
surface0 = "#313244"
surface1 = "#45475A"
surface2 = "#585B70"
teal = "#94E2D5"
text = "#CDD6F4"
yellow = "#F9E2AF"

# One line prompt
[line_break]
disabled = false

[cmd_duration]
disabled = true

[hostname]
disabled = false
format = '[$ssh_symbol$hostname@]($style)'
ssh_only = false
ssh_symbol = "ïŒ "
style = "bold bg:base fg:green2"

[username]
disabled = false
format = '[$user]($style)'
show_always = true
style_root = "bold bg:base fg:green2"
style_user = "bold bg:base fg:green2"

[sudo]
disabled = false
format = '[$symbol]($style)'
style = "bold bg:base fg:rojo"
symbol = "ó°šŒ "

[directory]
disabled = false
format = '[$path]($style)[$readonly]($read_only_style)'
home_symbol = "ïŒ§  ~"
read_only = " ï ½"
read_only_style = "fg:red"
style = "bold bg:base fg:yellow"
truncate_to_repo = false
truncation_length = 99
truncation_symbol = ".../"

[env_var]
default = ""
disabled = true
format = "[$env_value]($style)"
style = "bold fg:text"
symbol = ""
variable = "VIRTUAL_ENV"

[git_branch]
disabled = false
symbol = "î‚ "
# symbol = "ï˜"
format = '[$symbol $branch(:$remote_branch)]($style)'
style = "bold bg:base fg:pink"

[git_commit]
disabled = false
format = '[#$hash$tag]($style)'
only_detached = false
style = "bold bg:base fg:pink"
tag_disabled = false
tag_symbol = "  ğŸ· "

[git_state]
disabled = false

[git_metrics]
added_style = "bold bg:base fg:green"
deleted_style = "bold bg:base fg:red"
disabled = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[git_status]
ahead = 'â‡¡'
behind = 'â‡£'
conflicted = '='
deleted = 'âœ˜'
disabled = false
diverged = 'â‡•'
format = '([\[$all_status$ahead_behind\]]($style) )'
modified = '!'
renamed = 'Â»'
staged = '+'
stashed = '\$'
style = "bold bg:base fg:red"
untracked = '?'
up_to_date = ''

[time]
disabled = true
format = '[$time]($style)'
style = "bold fg:yellow"
time_format = "%b %d, %T"

[aws]
disabled = false
symbol = "îŒ½  "

[c]
disabled = false
# detect_extensions = ['c', 'h', 'cpp', 'hpp']
format = '[\[$symbol($version(-$name))\]]($style)'
symbol = "î˜ "

[conda]
disabled = false
format = 'via [$symbol$environment]($style) '
ignore_base = true
style = 'bold fg:green'
symbol = "ï„Œ "

[docker_context]
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
disabled = false
only_with_files = true
symbol = "ïŒˆ "

[golang]
disabled = false
format = '[\[$symbol$version\]]($style)'
symbol = "î˜§ "

[haskell]
disabled = false
symbol = "î· "

[hg_branch]
disabled = false
symbol = "ï˜ "

[java]
disabled = false
format = '[\[$symbol$version\]]($style)'
symbol = "î‰– "

[julia]
disabled = false
symbol = "î˜¤ "

[lua]
disabled = false
format = '[\[$symbol$version\]]($style)'
symbol = "î˜  "

[nodejs]
disabled = false
symbol = "îœ˜ "

[package]
disabled = false
symbol = "ï£– "

[python]
disabled = false
format = '[\[$symbol$version( ï‚¬ $virtualenv)\]]($style)'
symbol = "îˆµ "

[rust]
disabled = false
format = '[\[$symbol($version)\]]($style)'
symbol = "î¨ "

[fill]
disabled = false
symbol = " "

[character]
disabled = false
error_symbol = "[âœ](bold fg:red)"
success_symbol = "[âœ](bold fg:rojo)"
vicmd_symbol = "[âœ](bold fg:mauve)"
# success_symbol = """
# [\
# â•· 
# â•°â”€â—¯](fg:green)"""
# error_symbol = """
# [\
# â•· 
# â•°â”€â—¯](fg:red)"""
# vimcmd_symbol = """
# [\
# â•· 
# â•°â”€â—¯](fg:mauve)"""
format = "$symbol "
